version = 1
test_patterns = ["tests/**", "test_*.py"]
exclude_patterns = ['docs/source/conf.py']

[[analyzers]]
name = "python"
enabled = true

[analyzers.meta]
runtime_version = "3.x.x"
type_checker = "mypy"
max_line_length = 88
